Fish 1515 - New Snapshot Version
payara/patched-src-grizzly pull request #34
Opened 2022-05-13 12:42 UTC by luiseufrasio

2022-05-13 12:59 UTC, JamesHillyard requested changes, later dismissed

2022-05-13 12:59 UTC, JamesHillyard commented on pom.xml
> -    <version>2.4.4.payara-p8</version>
Parent version in this file is still 2.4.4.payara-p8 (Line 26)

2022-05-13 16:24 UTC, luiseufrasio commented on pom.xml
> -    <version>2.4.4.payara-p8</version>
Done!

2022-05-13 16:36 UTC, Pandrex247 requested changes
This doesn't compile - I think your import changes are wrong.
`HttpServerFilter` cannot find:
* `EmptyCompletionHandler`
* `FilterChainEvent`
* `TransportFilter`

2022-06-06 09:28 UTC, Pandrex247 approved these changes

2022-06-06 10:45 UTC, merged