Fish 9690 filtering incorrect characters from header rfc 9110
payara/patched-src-grizzly pull request #39
Opened 2024-11-12 04:05 UTC by breakponchito

2024-11-22 11:40 UTC, Pandrex247 requested changes
Please rework to be semantically compatible with a minor version update (no breaking API changes)

2024-12-06 18:04 UTC, breakponchito commented
> Please rework to be semantically compatible with a minor version update (no breaking API changes)

already fix the issue for the semantic versioning

2024-12-09 10:42 UTC, Pandrex247 submitted a review, later dismissed
This is changing an existing Grizzly 4.0.0 patched branch to a 4.0.2 - this should be getting made to a new 4.0.2 maintenance branch, not updating an existing one

2024-12-09 10:42 UTC, Pandrex247 commented on modules/http/src/main/java/org/glassfish/grizzly/http/HttpCodecFilter.java
> +                if(parsingState.subState == 0 && parsingState.start== -1) {
```suggestion
                if (parsingState.subState == 0 && parsingState.start== -1) {
```

2024-12-09 10:42 UTC, Pandrex247 commented on modules/http/src/main/java/org/glassfish/grizzly/http/HttpCodecFilter.java
> +                if(!parseHeaderName(httpHeader, mimeHeaders, parsingState, input)){
```suggestion
                if (!parseHeaderName(httpHeader, mimeHeaders, parsingState, input)){
```

2024-12-09 21:53 UTC, breakponchito commented on modules/http/src/main/java/org/glassfish/grizzly/http/HttpCodecFilter.java
> +                if(parsingState.subState == 0 && parsingState.start== -1) {
already fix

2024-12-09 21:53 UTC, breakponchito commented on modules/http/src/main/java/org/glassfish/grizzly/http/HttpCodecFilter.java
> +                if(!parseHeaderName(httpHeader, mimeHeaders, parsingState, input)){
already fixed

2024-12-11 17:58 UTC, Pandrex247 requested changes
Needs rebasing onto 4.0.0 without all of the 4.0.2 commits

2024-12-11 18:45 UTC, closed without merging